# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81ec7f2a01e72efe1a40be448d10d8b867f741d1717934ed31ad34a348ed8edc0dd9a51ef0773a2d19f36effa6747ad738607521912a1ead5c53e1119e2a759e

test:
  secret_key_base: 79084980b59645c9259283989f57296402c310b3ebd9800c1fa0479fb2119dcd6063bf55485df02f07aa48d55ea9f72d99a1bfd3672034bb05ce1b6ad45f4579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
